# Generated by Django 4.2 on 2024-05-29 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='descripcion',
            field=models.CharField(default='No disponible', max_length=1000, verbose_name='Descripcion'),
        ),
    ]
