# Generated by Django 4.2 on 2024-05-21 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0005_alter_pedido_usuario_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direccion',
            name='usuario_cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ecommerce.usuariocliente'),
        ),
    ]
