# Generated by Django 4.2 on 2024-05-22 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0006_alter_direccion_usuario_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarioadministrador',
            name='roles',
            field=models.JSONField(default={}),
        ),
    ]
