# Generated by Django 4.2 on 2024-05-22 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0007_usuarioadministrador_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarioadministrador',
            name='roles',
            field=models.JSONField(default=dict),
        ),
    ]
