# Generated by Django 4.2 on 2024-05-22 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0008_alter_usuarioadministrador_roles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarioadministrador',
            name='roles',
        ),
        migrations.AddField(
            model_name='usuarioadministrador',
            name='rol',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('EDITOR', 'Editor'), ('VENDEDOR', 'Vendedor'), ('CLIENTE', 'Cliente')], default='Cliente', max_length=50),
        ),
    ]
