# Generated by Django 4.2 on 2024-05-22 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0009_remove_usuarioadministrador_roles_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarioadministrador',
            name='rol',
        ),
    ]
