# Generated by Django 4.2 on 2024-05-29 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0011_rol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rol',
            name='nombre_rol',
        ),
        migrations.AddField(
            model_name='rol',
            name='description',
            field=models.TextField(default='No description'),
        ),
        migrations.AddField(
            model_name='rol',
            name='rol',
            field=models.CharField(default='cliente', max_length=100),
        ),
        migrations.AddField(
            model_name='usuarioadministrador',
            name='roles',
            field=models.ManyToManyField(to='ecommerce.rol'),
        ),
        migrations.AddField(
            model_name='usuariocliente',
            name='roles',
            field=models.ManyToManyField(to='ecommerce.rol'),
        ),
        migrations.AlterModelTable(
            name='rol',
            table='rol',
        ),
    ]
