# Generated by Django 4.2 on 2024-05-29 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0012_remove_rol_nombre_rol_rol_description_rol_rol_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallepedido',
            name='is_cart',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='detallepedido',
            name='pedido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ecommerce.pedido'),
        ),
    ]
