# Generated by Django 5.0.4 on 2024-05-27 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0012_remove_rol_nombre_rol_rol_description_rol_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rol',
            name='description',
            field=models.TextField(default='No description'),
        ),
        migrations.AlterModelTable(
            name='rol',
            table='rol',
        ),
    ]
