# Generated by Django 5.0.4 on 2024-05-28 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0014_usuarioadministrador_roles_usuariocliente_roles'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rol',
            old_name='name',
            new_name='nombre',
        ),
    ]
