# Generated by Django 4.2 on 2024-05-29 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0015_rename_name_rol_nombre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historialpedido',
            old_name='pedido',
            new_name='pedido_id',
        ),
        migrations.RemoveField(
            model_name='rol',
            name='nombre',
        ),
        migrations.AddField(
            model_name='rol',
            name='rol',
            field=models.CharField(default='cliente', max_length=100),
        ),
        migrations.AlterField(
            model_name='libro',
            name='descripcion',
            field=models.CharField(default='No disponible', max_length=1000, verbose_name='Descripcion'),
        ),
    ]
