# Generated by Django 4.2 on 2024-05-28 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_libro', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('portada', models.ImageField(default='No disponible', upload_to='portadas/', verbose_name='Portada')),
                ('descripcion', models.CharField(default='No disponible', max_length=100, verbose_name='Descripcion')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField()),
            ],
        ),
    ]
